# Generated by Django 3.1.3 on 2022-01-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schueler',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Passwort_express', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=40)),
                ('Loginname', models.CharField(max_length=60)),
                ('Passwort', models.IntegerField()),
                ('SessionID', models.CharField(max_length=32)),
                ('Lehrername', models.CharField(max_length=30)),
                ('LehrerID', models.IntegerField()),
                ('Klassenname', models.CharField(max_length=30)),
                ('Geschlecht', models.CharField(max_length=20)),
                ('Klassenstufe', models.CharField(max_length=20)),
                ('Anmeldedatum', models.IntegerField()),
                ('Anmeldeklassenstufe', models.CharField(max_length=30)),
                ('Altklasse', models.CharField(max_length=30)),
                ('gesperrt', models.CharField(max_length=30)),
                ('Aufgaben', models.CharField(max_length=300)),
                ('Altaufgaben', models.CharField(max_length=600)),
                ('done', models.IntegerField()),
                ('Info', models.CharField(max_length=60)),
                ('interventiongroup', models.IntegerField()),
            ],
        ),
    ]
